Update build-and-compress.yml

diff --git a/.github/workflows/build-and-compress.yml b/.github/workflows/build-and-compress.yml
--- a/.github/workflows/build-and-compress.yml
+++ b/.github/workflows/build-and-compress.yml
@@ -7,27 +7,21 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:      
-      - name: Start frp tunnel
-        uses: cirunlabs/frp-tunnel-action@v1.2.0
-        with:
-          timeout_minutes: 1
-          frp_server: '{{ secrets.FRP_SERVER }}'
-          frp_token: '${{ secrets.FRP_TOKEN }}'
-          local_port: 22
-          remote_port: 6000
-
-      # 故意报错，提前终止
-      - name: Error step
-        run: |
-          echo "This step is intentionally failing to demonstrate error handling."
-          exit 1
-
       - uses: actions/checkout@v4
 
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
           python-version: "3.10"
+
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+
+      # 故意报错，提前终止
+      - name: Error step
+        run: |
+          echo "This step is intentionally failing to demonstrate error handling."
+          exit 1
 
       - name: Install dependencies
         run: |
